#!/usr/bin/env python3
"""Backfill NULL metadata columns in TRANSCRIPTION_RESULTS by re-deriving them.

DRY RUN BY DEFAULT. Writing requires --execute AND a prior --clone-backup.

    # 1. see what is recoverable, touches nothing
    python scripts/backfill_metadata.py

    # 2. per-row detail for a spot check
    python scripts/backfill_metadata.py --show 20

    # 3. take the free zero-copy safety net
    python scripts/backfill_metadata.py --clone-backup

    # 4. write (refuses unless the backup from step 3 exists)
    python scripts/backfill_metadata.py --execute

WHAT THIS FIXES

For roughly six months the notebook's helper cell was missing `import re`. The NameError fired on
the very first statement of parse_summary_sections, and the caller swallowed it in a bare
`except Exception: pass`, so ALL SIX parsed fields came back NULL - not just the title - with no
error recorded anywhere. Fixed 2026-08-18. Fill rates: 100% of rows processed after the fix have a
title, versus 42.5% before it.

The transcripts themselves are fine. SUMMARY_MARKDOWN, TRANSCRIPT, TRANSCRIPT_WITH_SPEAKERS and
SRT_CONTENT were all written before the parser ran, so the inputs needed to re-derive the parsed
columns are still sitting in the table. This re-runs the (now tested) functions over them.

SAFETY PROPERTIES, in order of how much they matter

1. Dry run is the default. --execute is required to write, and is refused unless the clone backup
   exists.
2. Only ever writes to columns that are currently NULL, via `WHERE <col> IS NULL`. A non-NULL value
   is never overwritten, so a correct row cannot be damaged by a wrong re-derivation.
3. Never touches TRANSCRIPT, TRANSCRIPT_WITH_SPEAKERS, SRT_CONTENT, SRT_WITH_SPEAKERS or
   SUMMARY_MARKDOWN. Those are the irreplaceable columns - they cannot be regenerated without the
   original media and a GPU. This script only writes the cheap derived ones.
4. Every UPDATE is keyed on FILE_NAME with a literal value, one row at a time. There is no
   bulk UPDATE whose WHERE clause could be wrong in a way that touches everything.
5. Reuses scripts/payload/transcribe_functions.py - the module under 122 offline tests - rather
   than reimplementing the parsers. A backfill written from a second implementation would be
   validating nothing.

TWO TRAPS THIS SCRIPT HANDLES, both found while building the parity suite

- SUMMARY_MARKDOWN is a WRAPPER document. generate_summary_markdown stores
  '# Transcription Summary: ... --- <llm text> --- *Generated by Snowflake Cortex AI*' but passes
  only the inner <llm text> to the parser. Feeding the stored column in directly sweeps the
  40-character footer into whichever section is last, silently corrupting QUESTIONS_RAISED on every
  row. inner_summary() below strips the wrapper.

- The '##'-HEADER ERA IS NOT RECOVERABLE with the current parser. Rows processed between
  2026-02-10 and 2026-08-17 have '## Key Topics'-style markdown headings, and
  parse_summary_sections matches bare headers by exact string equality, so it extracts nothing from
  them. Those rows are reported separately as UNRECOVERABLE rather than being counted as failures
  or silently skipped - deciding what to do about them is a judgement call, not this script's to
  make. MEETING_TITLE is unaffected in either era because it is regex-matched.
"""

import argparse
import json
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, 'scripts', 'payload'))

import transcribe_functions as tf  # noqa: E402

CONNECTION = os.environ.get('SNOW_CONNECTION', 'DEMO')
TABLE = 'TRANSCRIPTION_DB_V2.TRANSCRIPTION_SCHEMA_V2.TRANSCRIPTION_RESULTS'
BACKUP = 'TRANSCRIPTION_DB_V2.TRANSCRIPTION_SCHEMA_V2.TR_BACKFILL_BACKUP'

# Columns this script is permitted to write. Anything not in this set is untouchable.
# Deliberately excludes TRANSCRIPT, TRANSCRIPT_WITH_SPEAKERS, SRT_CONTENT, SRT_WITH_SPEAKERS and
# SUMMARY_MARKDOWN: those cannot be regenerated without the original media and a GPU.
WRITABLE = (
    'MEETING_TITLE', 'CALL_BRIEF', 'KEY_POINTS', 'NEXT_STEPS',
    'DECISIONS_MADE', 'QUESTIONS_RAISED', 'ACCOUNT_NAME', 'CALL_START_TS',
)

SUMMARY_COLS = ('MEETING_TITLE', 'CALL_BRIEF', 'KEY_POINTS', 'NEXT_STEPS',
                'DECISIONS_MADE', 'QUESTIONS_RAISED')

# The wrapper generate_summary_markdown puts around the LLM output.
_FOOTER = '\n---\n*Generated by Snowflake Cortex AI*'
_SEP = '\n---\n'

# Detects the 2026-02-10..2026-08-17 header format the current parser cannot read.
_OFF_ERA = ('## Summary', '## Key Topics', '## Follow-up Items',
            '## Decisions Made', '## Questions Raised')

# --- ACCOUNT_NAME sanity filter (used by --strict) --------------------------------
#
# parse_filename_metadata takes the second '_'-delimited field as the account, which is only
# correct when the filename follows the 'DATE_ACCOUNT_description.ext' convention. It does not
# validate, so non-conforming filenames yield confident garbage. Measured over the 220 values this
# backfill would write:
#
#     194  match an account already present in the table, on a dated filename   - trustworthy
#      16  unknown but plausible (RMS, VivianHealth, Angi.com, Rich.Badurski)   - new accounts
#       8  carry a file extension, because the filename had no separator after  - WRONG
#          the date, so the whole description became the "account"
#       2  come from undated filenames ('overview', 'CS')                       - WRONG
#
# The 10 wrong ones are the same defect already present in stored data - the existing column
# contains 'Badurski.SE.Team.meeting.mp4', '2-2.meeting.with.Rich.TJ.and.Adam.mp4' and 'by'. So
# writing them is consistent with history rather than novel damage. --strict declines to add more.
_MEDIA_EXT = re.compile(r'\.(mp4|mp3|m4a|wav|mov|avi|mkv)$', re.I)
_DATED_FILENAME = re.compile(r'^\d{4}-\d{2}-\d{2}')


def account_looks_wrong(file_name, account):
    """Conservative reject: only flags values that are definitely not an account name.

    Deliberately does NOT reject merely-unfamiliar names - 16 of the planned values are real
    accounts that simply have no row in the table yet, and dropping them would be a worse error
    than keeping them.
    """
    if _MEDIA_EXT.search(account):
        return 'value carries a media file extension'
    if not _DATED_FILENAME.match(file_name):
        return 'filename has no leading date, so field 2 is not the account'
    return None


def inner_summary(markdown):
    """Recover the raw LLM text the parser was originally given. See module docstring."""
    if not markdown:
        return markdown
    body = markdown
    idx = body.rfind(_FOOTER)
    if idx != -1:
        body = body[:idx]
    idx = body.find(_SEP)
    if idx != -1:
        body = body[idx + len(_SEP):]
    return body.strip()


def is_off_era(inner):
    """True when the content uses '##'-prefixed section headers."""
    return any(('\n' + h) in ('\n' + inner) or inner.startswith(h) for h in _OFF_ERA)


def run_sql(sql, fetch=True):
    proc = subprocess.run(
        ['snow', 'sql', '-q', sql, '--connection', CONNECTION,
         '--enable-templating', 'NONE', '--format', 'json'],
        capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout + proc.stderr)
        raise SystemExit('snow sql failed (rc=%d)' % proc.returncode)
    if not fetch:
        return []
    try:
        data = json.loads(proc.stdout)
    except ValueError:
        return []
    rows = []
    for block in (data if isinstance(data, list) else [data]):
        for row in (block if isinstance(block, list) else [block]):
            if isinstance(row, dict):
                rows.append(row)
    return rows


def sql_str(value):
    """Single-quoted SQL literal with quotes doubled. Values here are LLM text and filenames."""
    return "'" + str(value).replace("'", "''") + "'"


def fetch_candidates():
    """Rows where at least one writable column is NULL but its input is present."""
    null_any = ' OR '.join('%s IS NULL' % c for c in WRITABLE)
    return run_sql("""
        SELECT FILE_NAME, SUMMARY_MARKDOWN, TRANSCRIPTION_TIMESTAMP,
               MEETING_TITLE, CALL_BRIEF, KEY_POINTS, NEXT_STEPS,
               DECISIONS_MADE, QUESTIONS_RAISED, ACCOUNT_NAME, CALL_START_TS
        FROM %s
        WHERE (%s)
        ORDER BY TRANSCRIPTION_TIMESTAMP
    """ % (TABLE, null_any))


def plan_row(row, strict=False):
    """Compute the set of column updates this row would receive. No side effects.

    Returns (updates, unrecoverable, rejected).
    """
    updates = {}
    unrecoverable = []
    rejected = []

    md = row.get('SUMMARY_MARKDOWN')
    if md:
        inner = inner_summary(md)
        parsed = tf.parse_summary_sections(inner)
        off_era = is_off_era(inner)
        for col in SUMMARY_COLS:
            if row.get(col) is not None:
                continue                      # never overwrite an existing value
            key = col.lower()
            value = parsed.get(key)
            if value:
                updates[col] = value
            elif off_era and col != 'MEETING_TITLE':
                unrecoverable.append(col)

    meta = tf.parse_filename_metadata(row['FILE_NAME'])
    if row.get('ACCOUNT_NAME') is None and meta.get('account_name'):
        why = account_looks_wrong(row['FILE_NAME'], meta['account_name'])
        if why and strict:
            rejected.append(('ACCOUNT_NAME', meta['account_name'], why))
        else:
            updates['ACCOUNT_NAME'] = meta['account_name']
    if row.get('CALL_START_TS') is None and meta.get('call_start_ts'):
        updates['CALL_START_TS'] = meta['call_start_ts'].strftime('%Y-%m-%d %H:%M:%S')

    return updates, unrecoverable, rejected


def build_update(file_name, updates):
    """One UPDATE per row, keyed on FILE_NAME, with IS NULL guards on every column.

    The IS NULL guards are redundant with plan_row's checks and are kept anyway: they make the
    statement safe on its own terms, so a stale plan cannot overwrite a value written since.
    """
    sets = []
    for col, value in sorted(updates.items()):
        if col not in WRITABLE:
            raise AssertionError('refusing to write non-writable column %s' % col)
        if col == 'CALL_START_TS':
            sets.append("%s = CASE WHEN %s IS NULL THEN TO_TIMESTAMP_NTZ(%s) ELSE %s END"
                        % (col, col, sql_str(value), col))
        else:
            sets.append("%s = CASE WHEN %s IS NULL THEN %s ELSE %s END"
                        % (col, col, sql_str(value), col))
    return "UPDATE %s SET %s WHERE FILE_NAME = %s" % (
        TABLE, ', '.join(sets), sql_str(file_name))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--execute', action='store_true',
                    help='actually write. Requires the clone backup to exist.')
    ap.add_argument('--clone-backup', action='store_true',
                    help='create the zero-copy backup clone, then exit')
    ap.add_argument('--show', type=int, default=0, metavar='N',
                    help='print the first N planned row updates')
    ap.add_argument('--limit', type=int, default=0,
                    help='only consider the first N candidate rows')
    ap.add_argument('--strict', action='store_true',
                    help='skip ACCOUNT_NAME values that are definitely not account names '
                         '(carry a media extension, or come from an undated filename). '
                         'Declines ~10 of 220 values.')
    ap.add_argument('--columns', default='',
                    help='comma-separated subset of columns to write, e.g. '
                         '"MEETING_TITLE,CALL_START_TS". Default: all writable columns.')
    args = ap.parse_args()

    selected = WRITABLE
    if args.columns:
        selected = tuple(c.strip().upper() for c in args.columns.split(',') if c.strip())
        bad = [c for c in selected if c not in WRITABLE]
        if bad:
            raise SystemExit('not writable: %s. Allowed: %s' % (bad, list(WRITABLE)))

    if args.clone_backup:
        print('Creating zero-copy backup %s' % BACKUP)
        run_sql('CREATE OR REPLACE TABLE %s CLONE %s' % (BACKUP, TABLE), fetch=False)
        n = run_sql('SELECT COUNT(*) AS N FROM %s' % BACKUP)[0]['N']
        print('  backup holds %s rows. Safe to run --execute now.' % n)
        return 0

    total = run_sql('SELECT COUNT(*) AS N FROM %s' % TABLE)[0]['N']
    rows = fetch_candidates()
    if args.limit:
        rows = rows[:args.limit]

    print('Table %s' % TABLE)
    print('  rows total                       %s' % total)
    print('  rows with at least one NULL      %s' % len(rows))
    print()

    per_col = {c: 0 for c in WRITABLE}
    unrec_col = {c: 0 for c in WRITABLE}
    planned, unrec_rows, untouched = [], set(), 0
    rejected_all = []

    for row in rows:
        updates, unrecoverable, rejected = plan_row(row, strict=args.strict)
        updates = {c: v for c, v in updates.items() if c in selected}
        rejected_all += [(row['FILE_NAME'],) + r for r in rejected]
        for c in updates:
            per_col[c] += 1
        for c in unrecoverable:
            unrec_col[c] += 1
            unrec_rows.add(row['FILE_NAME'])
        if updates:
            planned.append((row['FILE_NAME'], updates))
        else:
            untouched += 1

    if selected != WRITABLE:
        print('COLUMN SUBSET: writing only %s' % ', '.join(selected))
        print()
    print('RECOVERABLE - would be written:')
    for c in WRITABLE:
        flag = '' if c in selected else '   (excluded by --columns)'
        print('    %-18s %4d%s' % (c, per_col[c], flag))
    print('  rows receiving >=1 update        %s' % len(planned))
    print()
    if args.strict:
        print('DECLINED by --strict - not plausible account names:')
        for fn, col, value, why in rejected_all[:12]:
            print('    %-52s %r' % (fn[:52], value))
            print('        %s' % why)
        if len(rejected_all) > 12:
            print('    ... and %d more' % (len(rejected_all) - 12))
        print('  total declined                   %s' % len(rejected_all))
        print()
    print("UNRECOVERABLE - '##'-header era (2026-02-10..2026-08-17), parser cannot read these:")
    for c in WRITABLE:
        if unrec_col[c]:
            print('    %-18s %4d' % (c, unrec_col[c]))
    print('  distinct rows affected           %s' % len(unrec_rows))
    print()
    print('  rows with NULLs but nothing derivable  %s' % untouched)
    print()

    if args.show:
        print('First %d planned updates:' % min(args.show, len(planned)))
        for file_name, updates in planned[:args.show]:
            print('  %s' % file_name[:72])
            for col, value in sorted(updates.items()):
                shown = str(value).replace('\n', ' \\n ')
                print('      %-16s %s' % (col, shown[:90]))
        print()

    if not args.execute:
        print('DRY RUN. Nothing was written.')
        print('Next: --show 20 to spot-check, then --clone-backup, then --execute.')
        return 0

    # ---- write path ----
    exists = run_sql("SELECT COUNT(*) AS N FROM INFORMATION_SCHEMA.TABLES "
                     "WHERE TABLE_SCHEMA = 'TRANSCRIPTION_SCHEMA_V2' "
                     "AND TABLE_NAME = 'TR_BACKFILL_BACKUP'")
    if not exists or not int(exists[0]['N']):
        raise SystemExit('REFUSING TO WRITE: backup %s does not exist. Run --clone-backup first.'
                         % BACKUP)

    print('Backup present. Writing %d rows...' % len(planned))
    done = 0
    for file_name, updates in planned:
        run_sql(build_update(file_name, updates), fetch=False)
        done += 1
        if done % 25 == 0:
            print('  %d/%d' % (done, len(planned)))
    print('  %d/%d done' % (done, len(planned)))

    after = run_sql('SELECT COUNT(*) AS N FROM %s' % TABLE)[0]['N']
    print()
    print('Row count before %s, after %s' % (total, after))
    if int(after) != int(total):
        raise SystemExit('ROW COUNT CHANGED. Investigate immediately; %s holds the original.'
                         % BACKUP)
    print('Row count unchanged, as expected - this script only fills NULLs.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
